[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Julian Boronat <julian.boronat>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pymongo = "^4.17.0"
fastapi = "^0.141.1"
uvicorn = "^0.52.3"
python-dotenv = "^1.2.3"
langchain-mongodb = "^0.11.0"
langchain-aws = "^1.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
