env:
  NODE_ENV: prod
  AWS_REGION: us-east-1
  NEXT_PUBLIC_API_BASE: https://rag-insurance-backend.industrysolutions.prod.corp.mongodb.com

envSecrets:
   MONGO_URI: rag-insurance-secrets
   AWS_KEY_REGION: rag-insurance-secrets

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"